{"uuid":"3e71e4cd-a70e-4070-9880-c6e291ae3d76","name":"Scenario Outline: Verify that user receives error for invalid python code for Max Consecutive Ones Question","children":["b8daf203-3aa1-4a16-a2c7-57f46700fa46"],"befores":[{"name":"hooks.HooksPage.setUp()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746753641520,"stop":1746753649222}],"afters":[{"name":"hooks.HooksPage.tearDown()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746753673936,"stop":1746753705001}],"start":1746753641519,"stop":1746753705002}