{"uuid":"447190c8-2606-4fec-9dbe-5b66ef62ee9e","name":"Scenario Outline: Verify that user receives error for invalid python code for Max Consecutive Ones Question","children":["dd379d77-77dc-47f1-9a4f-07be62024d2f"],"befores":[{"name":"hooks.HooksPage.setUp()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1747073346757,"stop":1747073348877}],"afters":[{"name":"hooks.HooksPage.tearDown(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1747073351780,"stop":1747073351912}],"start":1747073346757,"stop":1747073351912}