{"uuid":"76c59984-0834-4793-96cd-2f0280a19021","name":"Scenario Outline: Verify that user receives error for invalid python code for Max Consecutive Ones Question","children":["5e25690b-b569-4ffa-aa1c-73aaf2af4ecd"],"befores":[{"name":"hooks.HooksPage.setUp()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746990101438,"stop":1746990110428}],"afters":[{"name":"hooks.HooksPage.tearDown()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746990125287,"stop":1746990125627}],"start":1746990101438,"stop":1746990125628}