{"uuid":"b8385a53-2130-4dac-a4bb-045ac2bc2f90","name":"Scenario Outline: Verify that user receives error for invalid python code for Max Consecutive Ones Question","children":["48c6b6df-47f8-44f1-ab0b-9444552d8f9b"],"befores":[{"name":"hooks.HooksPage.setUp()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1747069185113,"stop":1747069187541}],"afters":[{"name":"hooks.HooksPage.tearDown(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1747069190687,"stop":1747069190837}],"start":1747069185112,"stop":1747069190837}